version: '3'

services:

  armor:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile
    image: armor-1.0
    container_name: armor
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: armor
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./config/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - nginx
      - mysql
      - redis
    networks:
      - armor-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
      - "4863:4863"
    volumes:
      - ./:/var/www
      - ./config/docker/nginx:/etc/nginx/conf.d
      - ./config/docker/nginx:/var/log/nginx
    networks:
      - armor-network

  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: armor
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: armor
      MYSQL_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./config/docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf'
    networks:
      - armor-network

  redis:
    image: redis:5.0
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
      - ./config/docker/redis/redis.conf:/etc/redis/redis.conf
    networks:
      - armor-network


#Docker Networks
networks:
  armor-network:
    driver: bridge


#Volumes
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local


