
table_name: armor_migrations

author:
  username: mdizak
  full_name: Matt Dizak
  email: mdizak@apexpl.io

packages:

  apex/armor:
    dir: ../vendor/apex/armor/config/migrations
    namespace: "Apex\\Armor\\Migrations"


